version: '3'

services:
  traefik:
    image: traefik:1.7-alpine
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt:/etc/letsencrypt
      - ./traefik.prod.toml:/traefik.toml
      - /data/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:traefik.sstechvn.com"
      - "traefik.port=8080"

networks:
  traefik:
    external:
      name: traefik_proxy
