version: "3.7"

services:
  app:
    image: personal-transaction-pro
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
      - ./Gemfile:/app/Gemfile
      - ./Gemfile.lock:/app/Gemfile.lock
      - ./package.json:/app/package.json
      - cache:/cache
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=pt_db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=
      - RACK_ENV=production
      - RAILS_ENV=production
      - REDIS_HOST=redis
      - SPROCKETS_CACHE=/cache
    labels:
      - "traefik.docker.network=traefik_proxy"
      - "traefik.enable=true"
      - "traefik.backend=app"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:pt.local.dev;PathPrefix:/"
      - "traefik.tags=app"
    networks:
      - traefik
  db:
    image: bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=pt_db
      - MARIADB_PASSWORD=pt_db
      - MARIADB_DATABASE=pt_db
    ports:
      - 3330:3306
    networks:
      - traefik
  redis:
    image: 'bitnami/redis:latest'
    command: ["redis-server", "--protected-mode", "no"]
    ports:
    - "6380:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik_proxy

volumes:
  cache:


