version: "3.7"

services:
  elasticsearch:
    image: "bitnami/elasticsearch:6.8.11"
    restart: always
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - traefik
    
networks:
  traefik:
    external:
      name: traefik_proxy
