version: "3.7"

services:
  mysql_56:
    image: 'bitnami/mariadb:latest'
    restart: always
    ports: 
      - '3306:3306'
    environment:
      - MARIADB_ROOT_USER=root
      - ALLOW_EMPTY_PASSWORD=true
    networks:
      - traefik
    volumes:
      - ./data:/bitnami/mariadb/data

networks:
  traefik:
    external:
      name: traefik_proxy